language: node_js

node_js:
  - "8"

cache: yarn

script:
  - yarn
  - yarn run lint
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: master
  local_dir: public
  on:
    branch: dev